services:
  - type: web
    name: site-audit-pro-lite
    runtime: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn site_audit_report.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: site-audit-pro-lite.onrender.com
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: https://site-audit-pro-lite.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: site-audit-pro-lite-db
          property: connectionString
      - key: CLOUDINARY_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false

databases:
  - name: site-audit-pro-lite-db
    plan: free