# Generated by Django 5.2.16 on 2026-09-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0009_reportentry_incident_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportproject',
            name='responsible_companies',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
