# Generated by Django 5.2.16 on 2026-09-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0010_reportproject_responsible_companies'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_image', models.FileField(blank=True, null=True, upload_to='site_logos/')),
                ('site_name', models.CharField(default='Site Audit Pro', max_length=120)),
                ('site_subtitle', models.CharField(default='Control visual de obra', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Branding del sitio',
                'verbose_name_plural': 'Branding del sitio',
            },
        ),
    ]
