# Generated by Django 5.2.16 on 2026-09-08 06:23

import report_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0011_sitebranding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryimage',
            name='image',
            field=models.FileField(upload_to=report_app.models.entry_image_upload_to),
        ),
        migrations.AlterField(
            model_name='projectplan',
            name='file',
            field=models.FileField(upload_to=report_app.models.project_plan_upload_to),
        ),
        migrations.AlterField(
            model_name='projectreport',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to=report_app.models.report_cover_upload_to),
        ),
        migrations.AlterField(
            model_name='reportproject',
            name='project_image',
            field=models.FileField(blank=True, null=True, upload_to=report_app.models.project_image_upload_to),
        ),
        migrations.AlterField(
            model_name='sitebranding',
            name='logo_image',
            field=models.FileField(blank=True, null=True, upload_to=report_app.models.site_logo_upload_to),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to=report_app.models.profile_image_upload_to),
        ),
    ]
